import { createAction } from '@reduxjs/toolkit'

export const createNewQuizLoading = createAction('quiz/createNew/loading')
export const createNewQuizSuccess = createAction('quiz/createNew/success')
export const createNewQuizError = createAction('quiz/createNew/error')
export const createNewQuizReset = createAction('quiz/createNew/reset')
export const getMyQuizLoading = createAction('quiz/getMyQuiz/loading')
export const getMyQuizSuccess = createAction('quiz/getMyQuiz/success')
export const getMyQuizError = createAction('quiz/getMyQuiz/error')
export const getQuizLoading = createAction('quiz/getQuiz/loading')
export const getQuizSuccess = createAction('quiz/getQuiz/success')
export const getQuizError = createAction('quiz/getQuiz/error')
export const getQuizByIdLoading = createAction('quiz/getQuizById/loading')
export const getQuizByIdSuccess = createAction('quiz/getQuizById/success')
export const getQuizByIdError = createAction('quiz/getQuizById/error')
export const updateMyQuizByIdLoading = createAction('quiz/updateMyQuizById/loading')
export const updateMyQuizByIdSuccess = createAction('quiz/updateMyQuizById/success')
export const updateMyQuizByIdError = createAction('quiz/updateMyQuizById/error')
export const deleteMyQuizByIdLoading = createAction('quiz/deleteMyQuizById/loading')
export const deleteMyQuizByIdSuccess = createAction('quiz/deleteMyQuizById/success')
export const deleteMyQuizByIdError = createAction('quiz/deleteMyQuizById/error')